export const Icons = {
  USER: require('../../assets/icons/user.png'),
  USER_ACTIVE: require('../../assets/icons/user-active.png'),
  HOME: require('../../assets/icons/home.png'),
  HOME_ACTIVE: require('../../assets/icons/home-active.png'),
  KEY: require('../../assets/icons/key.png'),
  KEY_CHECK: require('../../assets/icons/key-check.png'),
  SHOW_PASSWORD: require('../../assets/icons/show.png'),
  HIDE_PASSWORD: require('../../assets/icons/visibility.png'),
  BACK: require('../../assets/icons/back.png'),
  BACK_WHITE: require('../../assets/icons/back-white.png'),
  POST: require('../../assets/icons/post.png'),
  POST_ACTIVE: require('../../assets/icons/post-active.png'),
  DOWN: require('../../assets/icons/down.png'),
  EMAIL: require('../../assets/icons/email.png'),
  ID_CARD: require('../../assets/icons/id-card.png'),
  FILTER: require('../../assets/icons/ic-filter.png'),
  DOUBLE_CHECK: require('../../assets/icons/ic-double-check.png'),
  NO_IMAGE: require('../../assets/icons/ic-no-img.png'),
  PLUS_WHITE: require('../../assets/icons/ic-plus.png'),
  AUCTION_ACTIVE: require('../../assets/icons/auction_active.png'),
  AUCTION: require('../../assets/icons/auction.png'),

  //item user
  COIN: require('../../assets/icons/coin.png'),
  COINS: require('../../assets/icons/coins.png'),
  CLOCK: require('../../assets/icons/coins.png'),
  HISTORY: require('../../assets/icons/history.png'),
  RIGHT: require('../../assets/icons/right.png'),
  MAIL: require('../../assets/icons/ic-mail.png'),
  LOCATION: require('../../assets/icons/ic-location.png'),
  PHONE: require('../../assets/icons/ic-phone.png'),
  BROWSER: require('../../assets/icons/browser.png'),
  ADD_POST: require('../../assets/icons/file-add.png'),
  ADD_POST_ACTIVE: require('../../assets/icons/file-add-active.png'),
  SHARE: require('../../assets/icons/ic-share.png'),
  BELL: require('../../assets/icons/alarm.png'),
  WALLET: require('../../assets/icons/ic-wallet.png'),
  ROTATION: require('../../assets/icons/ic-rotation.png'),
  MAIN_MONEY: require('../../assets/icons/ic-money-gr.png'),
  MAIN_MONEY2: require('../../assets/icons/ic-money-red.png'),
  WORKFLOW: require('../../assets/icons/work.png'),
  WORKFLOW_ACTIVE: require('../../assets/icons/work-active.png'),
  FIN: require('../../assets/icons/fin.png'),
  FIN_ACTIVE: require('../../assets/icons/fin-active.png'),
  PRODUCT: require('../../assets/icons/product.png'),
  PRODUCT_ACTIVE: require('../../assets/icons/product-active.png'),
  MANAGER: require('../../assets/icons/manager.png'),
  MANAGER_ACTIVE: require('../../assets/icons/manager-active.png'),
  USER_COLOR: require('../../assets/icons/user-color.png'),
  USER_COLOR_GROUP: require('../../assets/icons/user-color-group.png'),
  USER_CONTACT: require('../../assets/icons/user-icon-contact.png'),
  WORKFLOW_COLOR: require('../../assets/icons/workflow.png'),

  //toast
  TOAST_DEFAULT: require('../../assets/icons/ic-notification.png'),
  TOAST_SUCCESS: require('../../assets/icons/ic-success.png'),
  TOAST_WARNING: require('../../assets/icons/ic-warning.png'),
  TOAST_ERROR: require('../../assets/icons/ic-error.png'),
  CANCEL: require('../../assets/icons/ic-cancel.png'),
  //brand
  MOMO: require('../../assets/icons/momo.png'),
  VNPAY: require('../../assets/icons/vnpay.png'),
};
export const Images = {
  SPACE_DEFAULT: require('../../assets/images/urban-line-305.png'),
  BIG_IMAGE_ICON: require('../../assets/images/icons8-image-100.png'),
  NO_DATA: require('../../assets/images/nodata.png'),
  OCLOCK: require('../../assets/images/clip-1085.png'),
  PAINT: require('../../assets/images/paint.png'),
  LOGO: require('../../assets/images/logo.jpg'),
  TRUOC: require('../../assets/images/truoc.jpg'),
  SAU: require('../../assets/images/sau.jpg'),
};
